### ISSUE TITLE
 GITM vs JARVIS-1

### ISSUE THREAD

**Issue by pashok3d** [CraftJarvis/JARVIS-1#1]
Appreciate the great read. I wounder why GITM [Zhu et al., 2023] was not included in evaluation?

**Comment by zhwang4ai** [comment]
Thank you for your comment. JARVIS-1 focuses on how to use the **native interface** to complete tasks in Minecraft, so we use RGB images in the observation space and try to keep the action space as consistent as possible with humans (using mouse and keyboard). Detailed information about the action space and observation space can be found in Section B of the Appendix. Based on our knowledge, GITM uses handwritten API code as the action space and detailed block information obtained from the environment as observations, which is difficult to obtain in a typical Minecraft environment. Therefore, we believe that comparing it with GITM is unfair. 
The methods compared in the paper were all experiments conducted under the same environmental setting to ensure a fair comparison.
