### ISSUE TITLE
Release Date?

### ISSUE THREAD

**Issue by gautierdag** [CraftJarvis/JARVIS-1#2]
Hi,
Thanks for your paper. I was wondering if you had any idea when it might be ready to be open-sourced? 
I'm keen to build upon it. 
Thanks

**Comment by zhwang4ai** [comment]
Hi,

Thank you for your interest in our paper. We are currently in the process of finalizing and organizing our code. We are working diligently with the goal of open-sourcing it before the end of the year. Please stay tuned for updates.

Thanks again for your interest and patience.

**Comment by jun0wanan** [comment]
> Hi,
> 
> Thank you for your interest in our paper. We are currently in the process of finalizing and organizing our code. We are working diligently with the goal of open-sourcing it before the end of the year. Please stay tuned for updates.
> 
> Thanks again for your interest and patience.

Thanks!

**Comment by gautierdag** [comment]
@zhwang4ai any updates?
