### ISSUE TITLE
Do you still have plan to open source the project?

### ISSUE THREAD

**Issue by lukaemon** [CraftJarvis/JARVIS-1#3]
Thx!

**Comment by zhwang4ai** [comment]
Thank you very much for your interest in our project. Our team is currently celebrating the Lunar New Year holiday, a period during which we take a short break to spend time with our families and recharge for the year ahead. As a result, we are momentarily pausing our work, including managing and sharing our project's resources.
However, we are indeed planning to make the source code of our JARVIS-1 framework publicly available on GitHub within a few weeks after our holiday break concludes. Feel free to contact us.

**Comment by lukaemon** [comment]
Happy new year! Thx.

**Comment by wrstt** [comment]
Yes!!

**Comment by spullara** [comment]
This project is very exciting to me as it turns out that OpenAI is doing nothing in their Assistant API for memory. Just truncating it. Was really hoping that a coherent plan for agent memory was forthcoming from them.
