### ISSUE TITLE
Do you still have plan to open source the project?

### ISSUE THREAD

**Issue by WZX0Swarm0Robotics** [CraftJarvis/JARVIS-1#4]

**Comment by cowboycodr** [comment]
Seems like it is abandoned. Unfortunate.

**Comment by WZX0Swarm0Robotics** [comment]
I have heard about your work more than once in related academic sharing and talks given by you and your team. I deeply admire your work for being so eye-opening and possessing efficient performance. I am also eagerly looking forward to seeing your open-source code and trying out this exciting and anticipated work myself. However, I noticed that it has been marked as "coming soon" on GitHub, and it was mentioned in February that the code would be released as soon as possible. Yet, to this day, it is still "coming soon," which is quite frustrating. I would be immensely grateful if you and your team could expedite the plan to publish the code.



---Original---
From: "Kian ***@***.***&gt;
Date: Mon, Mar 25, 2024 21:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CraftJarvis/JARVIS-1] Do you still have plan to open source theproject? (Issue #4)




 
Seems like it is abandoned. Unfortunate.

**Comment by wrstt** [comment]
Huh?

**Comment by zhwang4ai** [comment]
Thank you for your patience and interest in our project. We're excited to share that our code is ready and we're eager to share our work with all of you.

However, we've encountered a challenge. JARVIS-1 relies on a customized version of the Minecraft environment. This environment is crucial to our work, but directly open-sourcing it could conflict with the Minecraft community's guidelines. We understand the importance of adhering to the spirit of open source as well as respecting community rules, so we're actively looking for a solution that respects both.

While we haven't found an ideal solution yet, we commit to uploading the code components **within this month**. This will allow interested developers to start exploring, using, and contributing to our project.

Regarding the customized Minecraft environment, we're planning to address this issue through direct email contact. If you need access to this environment, please contact me via email after the code is released, and we will provide the necessary assistance and guidance.😄

**Comment by wrstt** [comment]
That’s so wild, how so?

**Comment by wrstt** [comment]
I would love a brief explanation on the Minecraft environment that is
really cool

**Comment by zhwang4ai** [comment]
Thank you for your patience and support during this time. We're pleased to announce that the environmental issues have been successfully resolved. Our team has worked diligently to promise the stability of JARVIS-1. We're excited to share that we plan to open-source the code of JARVIS-1 before the deadline of April 1, 23:59 AOE.
